// Code generated by variantgen. DO NOT EDIT.

package container

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed container.variants.json
var containerVariantsJSON []byte

var ContainerVariants = uiutils.MustParseVariantRecipe(containerVariantsJSON).ToVariants()

