// Code generated by variantgen. DO NOT EDIT.

package badge

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed badge.variants.json
var badgeVariantsJSON []byte

var BadgeVariants = uiutils.MustParseVariantRecipe(badgeVariantsJSON).ToVariants()

