// Code generated by variantgen. DO NOT EDIT.

package title

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed title.variants.json
var titleVariantsJSON []byte

var TitleVariants = uiutils.MustParseVariantRecipe(titleVariantsJSON).ToVariants()

