// Code generated by variantgen. DO NOT EDIT.

package block

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed block.variants.json
var blockVariantsJSON []byte

var BlockVariants = uiutils.MustParseVariantRecipe(blockVariantsJSON).ToVariants()

