// Code generated by variantgen. DO NOT EDIT.

package card

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed card.variants.json
var cardVariantsJSON []byte

var CardVariants = uiutils.MustParseVariantRecipe(cardVariantsJSON).ToVariants()

