// Code generated by variantgen. DO NOT EDIT.

package linebreak

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed linebreak.variants.json
var linebreakVariantsJSON []byte

var LinebreakVariants = uiutils.MustParseVariantRecipe(linebreakVariantsJSON).ToVariants()

