// Code generated by variantgen. DO NOT EDIT.

package iconbadge

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed iconbadge.variants.json
var iconbadgeVariantsJSON []byte

var IconbadgeVariants = uiutils.MustParseVariantRecipe(iconbadgeVariantsJSON).ToVariants()

