// Code generated by variantgen. DO NOT EDIT.

package textarea

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed textarea.variants.json
var textareaVariantsJSON []byte

var TextareaVariants = uiutils.MustParseVariantRecipe(textareaVariantsJSON).ToVariants()

