// Code generated by variantgen. DO NOT EDIT.

package icon

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed icon.variants.json
var iconVariantsJSON []byte

var IconVariants = uiutils.MustParseVariantRecipe(iconVariantsJSON).ToVariants()

