// Code generated by variantgen. DO NOT EDIT.

package label

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed label.variants.json
var labelVariantsJSON []byte

var LabelVariants = uiutils.MustParseVariantRecipe(labelVariantsJSON).ToVariants()

