// Code generated by variantgen. DO NOT EDIT.

package selectfield

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed select.variants.json
var selectVariantsJSON []byte

var SelectVariants = uiutils.MustParseVariantRecipe(selectVariantsJSON).ToVariants()

