// Code generated by variantgen. DO NOT EDIT.

package text

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed text.variants.json
var textVariantsJSON []byte

var TextVariants = uiutils.MustParseVariantRecipe(textVariantsJSON).ToVariants()

