// Code generated by variantgen. DO NOT EDIT.

package dialog

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed dialog.variants.json
var dialogVariantsJSON []byte

var DialogVariants = uiutils.MustParseVariantRecipe(dialogVariantsJSON).ToVariants()

