// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1001
/**


 * Dialog renders a native dialog root with optional behavior hook.


 */

// Copy: components/ui/dialog/dialog.templ

package dialog

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import (
	"strings"

	"github.com/fastygo/templ/utils"
)

var DialogVariants = uiutils.Variants{
	Base: "m-auto rounded-lg border border-border bg-background text-foreground shadow-lg backdrop:bg-background/80",
	Keys: []string{"variant", "size"},
	Defaults: map[string]string{
		"variant": "default",
		"size":    "default",
	},
	ByKey: map[string]map[string]string{
		"variant": {
			"default":  "",
			"card":     "bg-card text-card-foreground",
			"sheet":    "min-h-screen rounded-none",
			"unstyled": "",
		},
		"size": {
			"sm":      "w-full max-w-sm",
			"default": "w-full max-w-lg",
			"lg":      "w-full max-w-2xl",
			"xl":      "w-full max-w-4xl",
			"full":    "h-full w-full max-w-none",
		},
	},
}

// DialogProps configures native dialog.
type DialogProps struct {
	Variant         string
	Size            string
	Class           string
	ID              string
	Open            bool
	DataUI8Kit      string
	AriaLabel       string
	AriaLabelledBy  string
	AriaDescribedBy string
	Attrs           templ.Attributes
}

func DialogClasses(p DialogProps) string {
	return uiutils.Compose(DialogVariants, map[string]string{
		"variant": p.Variant,
		"size":    p.Size,
	}, p.Class)
}

func dialogAttrs(p DialogProps) templ.Attributes {
	attrs := uiutils.MergeAttrs(templ.Attributes{}, p.Attrs)
	if strings.TrimSpace(p.ID) != "" {
		attrs["id"] = p.ID
	}
	if strings.TrimSpace(p.DataUI8Kit) != "" {
		attrs["data-ui8kit"] = p.DataUI8Kit
	}
	if strings.TrimSpace(p.AriaLabel) != "" {
		attrs["aria-label"] = p.AriaLabel
	}
	if strings.TrimSpace(p.AriaLabelledBy) != "" {
		attrs["aria-labelledby"] = p.AriaLabelledBy
	}
	if strings.TrimSpace(p.AriaDescribedBy) != "" {
		attrs["aria-describedby"] = p.AriaDescribedBy
	}
	return attrs
}

// Dialog renders native dialog.
func Dialog(p DialogProps) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		var templ_7745c5c3_Var2 = []any{DialogClasses(p)}
		templ_7745c5c3_Err = templ.RenderCSSItems(ctx, templ_7745c5c3_Buffer, templ_7745c5c3_Var2...)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<dialog class=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var3 string
		templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(templ.CSSClasses(templ_7745c5c3_Var2).String())
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `ui/dialog/dialog.templ`, Line: 1, Col: 0}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		if p.Open {
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, " open")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
		}
		templ_7745c5c3_Err = templ.RenderAttributes(ctx, templ_7745c5c3_Buffer, dialogAttrs(p))
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 4, ">")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templ_7745c5c3_Var1.Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 5, "</dialog>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
