// Code generated by variantgen. DO NOT EDIT.

package link

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed link.variants.json
var linkVariantsJSON []byte

var LinkVariants = uiutils.MustParseVariantRecipe(linkVariantsJSON).ToVariants()

