// Code generated by variantgen. DO NOT EDIT.

package sheet

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed sheet.variants.json
var sheetVariantsJSON []byte

var SheetVariants = uiutils.MustParseVariantRecipe(sheetVariantsJSON).ToVariants()

