// Code generated by variantgen. DO NOT EDIT.

package table

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed table.variants.json
var tableVariantsJSON []byte

var TableVariants = uiutils.MustParseVariantRecipe(tableVariantsJSON).ToVariants()

