// Code generated by variantgen. DO NOT EDIT.

package checkbox

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed checkbox.variants.json
var checkboxVariantsJSON []byte

var CheckboxVariants = uiutils.MustParseVariantRecipe(checkboxVariantsJSON).ToVariants()

