// Code generated by variantgen. DO NOT EDIT.

package image

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed image.variants.json
var imageVariantsJSON []byte

var ImageVariants = uiutils.MustParseVariantRecipe(imageVariantsJSON).ToVariants()

