// Code generated by variantgen. DO NOT EDIT.

package alert

import (
	_ "embed"

	"github.com/fastygo/templ/utils"
)

//go:embed alert.variants.json
var alertVariantsJSON []byte

var AlertVariants = uiutils.MustParseVariantRecipe(alertVariantsJSON).ToVariants()

